---
title: "Installing the GNU Scientific Library (GSL)"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Installing the GNU Scientific Library (GSL)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# macOS

### Using Homebrew

1. **Install [`Homebrew`](https://brew.sh/) if it's not installed**:

```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

2. **Update `Homebrew` package list**:

```bash
brew update
```

3. **Install GSL**

```bash
brew install gsl
```

### Using MacPorts

1. **Install MacPorts if it's not installed**: Follow the installation guide on the [MacPorts website](https://www.macports.org/install.php).

2. **Update MacPorts package list**:

```bash
sudo port selfupdate
```

3. **Install GSL**:

```bash
sudo port install gsl
```

### Compiling from Source

1. **Download the source code**: Download the GSL source code from the [official website](https://www.gnu.org/software/gsl/).

2. **Unzip and navigate to the folder**:

```bash
tar -xzf gsl-x.y.z.tar.gz
cd gsl-x.y.z
```

Replace `x.y.z` with the version number.

3. **Configure and make**:

```bash
./configure
make
sudo make install
```


# Windows

Installing the GNU Scientific Library (GSL) on Windows can be a bit more challenging compared to Linux or macOS.

### Using MSYS2

1. **Install MSYS2**: Download and install MSYS2 from the [official site](https://www.msys2.org/).

2. **Update Package Database and Core System Packages**: Open MSYS2 and run the following commands to update the package database and core system packages.

```bash
pacman -Syu
```

After this, close MSYS2 and open it again.

3. **Update Remaining Packages**: Run the following command to update the remaining packages:

```bash
pacman -Su
```

4. **Install GSL**: To install GSL, run:

```bash
pacman -S mingw-w64-x86_64-gsl
```

### Using vcpkg (For Visual Studio)

1. **Clone vcpkg**: First, you'll need to clone the `vcpkg` repository and then bootstrap it.

```bash
git clone https://github.com/microsoft/vcpkg
cd vcpkg
bootstrap-vcpkg.bat
```

2. **Install GSL**: To install GSL, run:

```bash
vcpkg install gsl:x64-windows
```

Or for 32-bit,

```bash
vcpkg install gsl:x86-windows
```

3. **Integrate with Visual Studio**: To integrate `vcpkg` libraries with Visual Studio, you can run:

```bash
vcpkg integrate install
```

# Linux system

### Ubuntu/Debian

Open your terminal and run:

```bash
sudo apt update
sudo apt install libgsl-dev
```

### Fedora

```bash
sudo dnf install gsl-devel
```

### CentOS/RHEL

For CentOS/RHEL, you can use the `yum` package manager:

```bash
sudo yum install gsl-devel
```

### From Source

You can also compile GSL from source code on any Linux distribution:

1. **Download the source code**: You can download the GSL source code from the [official website](https://www.gnu.org/software/gsl/).

2. **Extract and navigate to the folder**:

```bash
tar -xzf gsl-x.y.z.tar.gz
cd gsl-x.y.z
```

Replace `x.y.z` with the version number.

3. **Configure, make, and install**:

```bash
./configure
make
sudo make install
```

After installation, you should be able to use the GSL in your development projects. The library and header files are generally placed in standard locations (`/usr/lib/`, `/usr/include/`, etc.), so you should not need to make any special arrangements to use them in your projects.


