// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// afmix
DataFrame afmix(std::string input_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<int> interval);
RcppExport SEXP _gauss_afmix(SEXP input_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP intervalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type interval(intervalSEXP);
    rcpp_result_gen = Rcpp::wrap(afmix(input_file, reference_index_file, reference_data_file, reference_pop_desc_file, interval));
    return rcpp_result_gen;
END_RCPP
}
// computeLD
List computeLD(int chr, long long int start_bp, long long int end_bp, DataFrame pop_wgt_df, std::string input_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<double> af1_cutoff);
RcppExport SEXP _gauss_computeLD(SEXP chrSEXP, SEXP start_bpSEXP, SEXP end_bpSEXP, SEXP pop_wgt_dfSEXP, SEXP input_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP af1_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< long long int >::type start_bp(start_bpSEXP);
    Rcpp::traits::input_parameter< long long int >::type end_bp(end_bpSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type pop_wgt_df(pop_wgt_dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type af1_cutoff(af1_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(computeLD(chr, start_bp, end_bp, pop_wgt_df, input_file, reference_index_file, reference_data_file, reference_pop_desc_file, af1_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// cpw2
DataFrame cpw2(std::string input_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<int> interval);
RcppExport SEXP _gauss_cpw2(SEXP input_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP intervalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type interval(intervalSEXP);
    rcpp_result_gen = Rcpp::wrap(cpw2(input_file, reference_index_file, reference_data_file, reference_pop_desc_file, interval));
    return rcpp_result_gen;
END_RCPP
}
// dist
DataFrame dist(int chr, long long int start_bp, long long int end_bp, long long int wing_size, std::string study_pop, std::string input_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<double> af1_cutoff);
RcppExport SEXP _gauss_dist(SEXP chrSEXP, SEXP start_bpSEXP, SEXP end_bpSEXP, SEXP wing_sizeSEXP, SEXP study_popSEXP, SEXP input_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP af1_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< long long int >::type start_bp(start_bpSEXP);
    Rcpp::traits::input_parameter< long long int >::type end_bp(end_bpSEXP);
    Rcpp::traits::input_parameter< long long int >::type wing_size(wing_sizeSEXP);
    Rcpp::traits::input_parameter< std::string >::type study_pop(study_popSEXP);
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type af1_cutoff(af1_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(dist(chr, start_bp, end_bp, wing_size, study_pop, input_file, reference_index_file, reference_data_file, reference_pop_desc_file, af1_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// distmix
DataFrame distmix(int chr, long long int start_bp, long long int end_bp, long long int wing_size, DataFrame pop_wgt_df, std::string input_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<double> af1_cutoff);
RcppExport SEXP _gauss_distmix(SEXP chrSEXP, SEXP start_bpSEXP, SEXP end_bpSEXP, SEXP wing_sizeSEXP, SEXP pop_wgt_dfSEXP, SEXP input_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP af1_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< long long int >::type start_bp(start_bpSEXP);
    Rcpp::traits::input_parameter< long long int >::type end_bp(end_bpSEXP);
    Rcpp::traits::input_parameter< long long int >::type wing_size(wing_sizeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type pop_wgt_df(pop_wgt_dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type af1_cutoff(af1_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(distmix(chr, start_bp, end_bp, wing_size, pop_wgt_df, input_file, reference_index_file, reference_data_file, reference_pop_desc_file, af1_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// jepeg
DataFrame jepeg(std::string study_pop, std::string input_file, std::string annotation_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<double> af1_cutoff);
RcppExport SEXP _gauss_jepeg(SEXP study_popSEXP, SEXP input_fileSEXP, SEXP annotation_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP af1_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type study_pop(study_popSEXP);
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type annotation_file(annotation_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type af1_cutoff(af1_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(jepeg(study_pop, input_file, annotation_file, reference_index_file, reference_data_file, reference_pop_desc_file, af1_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// jepegmix
DataFrame jepegmix(DataFrame pop_wgt_df, std::string input_file, std::string annotation_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<double> af1_cutoff);
RcppExport SEXP _gauss_jepegmix(SEXP pop_wgt_dfSEXP, SEXP input_fileSEXP, SEXP annotation_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP af1_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type pop_wgt_df(pop_wgt_dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type annotation_file(annotation_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type af1_cutoff(af1_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(jepegmix(pop_wgt_df, input_file, annotation_file, reference_index_file, reference_data_file, reference_pop_desc_file, af1_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// prep_qcat
List prep_qcat(int chr, long long int start_bp, long long int end_bp, long long int wing_size, std::string study_pop, std::string input_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<double> af1_cutoff);
RcppExport SEXP _gauss_prep_qcat(SEXP chrSEXP, SEXP start_bpSEXP, SEXP end_bpSEXP, SEXP wing_sizeSEXP, SEXP study_popSEXP, SEXP input_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP af1_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< long long int >::type start_bp(start_bpSEXP);
    Rcpp::traits::input_parameter< long long int >::type end_bp(end_bpSEXP);
    Rcpp::traits::input_parameter< long long int >::type wing_size(wing_sizeSEXP);
    Rcpp::traits::input_parameter< std::string >::type study_pop(study_popSEXP);
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type af1_cutoff(af1_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(prep_qcat(chr, start_bp, end_bp, wing_size, study_pop, input_file, reference_index_file, reference_data_file, reference_pop_desc_file, af1_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// prep_qcatmix
List prep_qcatmix(int chr, long long int start_bp, long long int end_bp, long long int wing_size, DataFrame pop_wgt_df, std::string input_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<double> af1_cutoff);
RcppExport SEXP _gauss_prep_qcatmix(SEXP chrSEXP, SEXP start_bpSEXP, SEXP end_bpSEXP, SEXP wing_sizeSEXP, SEXP pop_wgt_dfSEXP, SEXP input_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP af1_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< long long int >::type start_bp(start_bpSEXP);
    Rcpp::traits::input_parameter< long long int >::type end_bp(end_bpSEXP);
    Rcpp::traits::input_parameter< long long int >::type wing_size(wing_sizeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type pop_wgt_df(pop_wgt_dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type af1_cutoff(af1_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(prep_qcatmix(chr, start_bp, end_bp, wing_size, pop_wgt_df, input_file, reference_index_file, reference_data_file, reference_pop_desc_file, af1_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// qcat
DataFrame qcat(int chr, long long int start_bp, long long int end_bp, long long int wing_size, std::string study_pop, std::string input_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<double> af1_cutoff);
RcppExport SEXP _gauss_qcat(SEXP chrSEXP, SEXP start_bpSEXP, SEXP end_bpSEXP, SEXP wing_sizeSEXP, SEXP study_popSEXP, SEXP input_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP af1_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< long long int >::type start_bp(start_bpSEXP);
    Rcpp::traits::input_parameter< long long int >::type end_bp(end_bpSEXP);
    Rcpp::traits::input_parameter< long long int >::type wing_size(wing_sizeSEXP);
    Rcpp::traits::input_parameter< std::string >::type study_pop(study_popSEXP);
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type af1_cutoff(af1_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(qcat(chr, start_bp, end_bp, wing_size, study_pop, input_file, reference_index_file, reference_data_file, reference_pop_desc_file, af1_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// qcatmix
DataFrame qcatmix(int chr, long long int start_bp, long long int end_bp, long long int wing_size, DataFrame pop_wgt_df, std::string input_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<double> af1_cutoff);
RcppExport SEXP _gauss_qcatmix(SEXP chrSEXP, SEXP start_bpSEXP, SEXP end_bpSEXP, SEXP wing_sizeSEXP, SEXP pop_wgt_dfSEXP, SEXP input_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP af1_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< long long int >::type start_bp(start_bpSEXP);
    Rcpp::traits::input_parameter< long long int >::type end_bp(end_bpSEXP);
    Rcpp::traits::input_parameter< long long int >::type wing_size(wing_sizeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type pop_wgt_df(pop_wgt_dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type af1_cutoff(af1_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(qcatmix(chr, start_bp, end_bp, wing_size, pop_wgt_df, input_file, reference_index_file, reference_data_file, reference_pop_desc_file, af1_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// simulateLD
List simulateLD(int chr, long long int start_bp, long long int end_bp, DataFrame pop_wgt_df, int sim_size, std::string input_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<double> af1_cutoff);
RcppExport SEXP _gauss_simulateLD(SEXP chrSEXP, SEXP start_bpSEXP, SEXP end_bpSEXP, SEXP pop_wgt_dfSEXP, SEXP sim_sizeSEXP, SEXP input_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP af1_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< long long int >::type start_bp(start_bpSEXP);
    Rcpp::traits::input_parameter< long long int >::type end_bp(end_bpSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type pop_wgt_df(pop_wgt_dfSEXP);
    Rcpp::traits::input_parameter< int >::type sim_size(sim_sizeSEXP);
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type af1_cutoff(af1_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(simulateLD(chr, start_bp, end_bp, pop_wgt_df, sim_size, input_file, reference_index_file, reference_data_file, reference_pop_desc_file, af1_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// prep_zmix5
NumericVector prep_zmix5(std::string input_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<double> percentile, Rcpp::Nullable<int> interval);
RcppExport SEXP _gauss_prep_zmix5(SEXP input_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP percentileSEXP, SEXP intervalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type percentile(percentileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type interval(intervalSEXP);
    rcpp_result_gen = Rcpp::wrap(prep_zmix5(input_file, reference_index_file, reference_data_file, reference_pop_desc_file, percentile, interval));
    return rcpp_result_gen;
END_RCPP
}
// prep_zmix4
NumericMatrix prep_zmix4(std::string input_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<int> interval, Rcpp::Nullable<int> offset);
RcppExport SEXP _gauss_prep_zmix4(SEXP input_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP intervalSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type interval(intervalSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(prep_zmix4(input_file, reference_index_file, reference_data_file, reference_pop_desc_file, interval, offset));
    return rcpp_result_gen;
END_RCPP
}
// prep_zmix3
NumericMatrix prep_zmix3(std::string input_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<int> interval, Rcpp::Nullable<int> steps);
RcppExport SEXP _gauss_prep_zmix3(SEXP input_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP intervalSEXP, SEXP stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type interval(intervalSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type steps(stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(prep_zmix3(input_file, reference_index_file, reference_data_file, reference_pop_desc_file, interval, steps));
    return rcpp_result_gen;
END_RCPP
}
// prep_zmix2
NumericMatrix prep_zmix2(std::string input_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<int> interval, Rcpp::Nullable<int> offset);
RcppExport SEXP _gauss_prep_zmix2(SEXP input_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP intervalSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type interval(intervalSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(prep_zmix2(input_file, reference_index_file, reference_data_file, reference_pop_desc_file, interval, offset));
    return rcpp_result_gen;
END_RCPP
}
// prep_zmix
NumericMatrix prep_zmix(std::string input_file, std::string reference_index_file, std::string reference_data_file, std::string reference_pop_desc_file, Rcpp::Nullable<int> interval);
RcppExport SEXP _gauss_prep_zmix(SEXP input_fileSEXP, SEXP reference_index_fileSEXP, SEXP reference_data_fileSEXP, SEXP reference_pop_desc_fileSEXP, SEXP intervalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input_file(input_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_index_file(reference_index_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_data_file(reference_data_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type reference_pop_desc_file(reference_pop_desc_fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type interval(intervalSEXP);
    rcpp_result_gen = Rcpp::wrap(prep_zmix(input_file, reference_index_file, reference_data_file, reference_pop_desc_file, interval));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gauss_afmix", (DL_FUNC) &_gauss_afmix, 5},
    {"_gauss_computeLD", (DL_FUNC) &_gauss_computeLD, 9},
    {"_gauss_cpw2", (DL_FUNC) &_gauss_cpw2, 5},
    {"_gauss_dist", (DL_FUNC) &_gauss_dist, 10},
    {"_gauss_distmix", (DL_FUNC) &_gauss_distmix, 10},
    {"_gauss_jepeg", (DL_FUNC) &_gauss_jepeg, 7},
    {"_gauss_jepegmix", (DL_FUNC) &_gauss_jepegmix, 7},
    {"_gauss_prep_qcat", (DL_FUNC) &_gauss_prep_qcat, 10},
    {"_gauss_prep_qcatmix", (DL_FUNC) &_gauss_prep_qcatmix, 10},
    {"_gauss_qcat", (DL_FUNC) &_gauss_qcat, 10},
    {"_gauss_qcatmix", (DL_FUNC) &_gauss_qcatmix, 10},
    {"_gauss_simulateLD", (DL_FUNC) &_gauss_simulateLD, 10},
    {"_gauss_prep_zmix5", (DL_FUNC) &_gauss_prep_zmix5, 6},
    {"_gauss_prep_zmix4", (DL_FUNC) &_gauss_prep_zmix4, 6},
    {"_gauss_prep_zmix3", (DL_FUNC) &_gauss_prep_zmix3, 6},
    {"_gauss_prep_zmix2", (DL_FUNC) &_gauss_prep_zmix2, 6},
    {"_gauss_prep_zmix", (DL_FUNC) &_gauss_prep_zmix, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_gauss(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
